In [343]:
import numpy as np
import pandas as pd
import scipy.linalg as la
import statistics
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.decomposition import PCA
from scipy import stats


In [344]:
dataset = pd.DataFrame( pd.read_csv("Social_Network_Ads.csv"))

In [345]:

dataset.shape

(400, 4)

In [346]:
X = dataset.iloc[:, :3].values 
y = dataset.iloc[:, 3].values  

In [332]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(X)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)
mean = ex.mean(axis=0)
X= ex -mean
# X=ex

===Chi2 Stat===
6382.412841094187


===Degrees of Freedom===
798


===P-Value===
0.0


===Contingency Table===
[[1.39002545e-01 1.02630212e+01 1.90085980e+04]
 [1.46428097e-01 1.08112745e+01 2.00240423e+04]
 [3.14467768e-01 2.32182036e+01 4.30034673e+04]
 ...
 [1.46545035e-01 1.08199084e+01 2.00400335e+04]
 [2.41447398e-01 1.78268662e+01 3.30179317e+04]
 [2.63475563e-01 1.94532791e+01 3.60302832e+04]]


In [265]:
mean = X.mean(axis=0)

In [266]:
X= X -mean

In [333]:
X

array([[1.39002545e-01, 1.02630212e+01, 1.90085980e+04],
       [1.46428097e-01, 1.08112745e+01, 2.00240423e+04],
       [3.14467768e-01, 2.32182036e+01, 4.30034673e+04],
       ...,
       [1.46545035e-01, 1.08199084e+01, 2.00400335e+04],
       [2.41447398e-01, 1.78268662e+01, 3.30179317e+04],
       [2.63475563e-01, 1.94532791e+01, 3.60302832e+04]])

In [8]:
def cov1(a, b): 
#     print("hello")
    if len(a) != len(b): 
#         print("here")
        return 
    a_mean = np.mean(a) 
    b_mean = np.mean(b) 
    sum = 0 
    for i in range(0, len(a)): 
        sum += ((a[i] - a_mean) * (b[i] - b_mean)) 
    return sum/(len(a)-1)

def calc_cov(A):
#     print(A[0])
    N,M = A.shape
    n=0;
    ret = np.reshape(np.zeros(M*M),(M,M))
#     print(ret)
    for m in range(0,M):
        for j in range(0,M):
#             print(m,j)
#             print(A.iloc[:,j].values)
            ret[m][j] = (cov1(A[:,m],A[:,j]))/((statistics.stdev(A[:,m]))*statistics.stdev(A[:,j]))
#             print(ret[n][m])
    return ret;

In [92]:
ret= calc_cov(X)

In [268]:
ret = np.cov(X.T)
ret

array([[2.50526316e-01, 3.86917293e-01, 1.03140351e+03],
       [3.86917293e-01, 1.09890702e+02, 5.54873810e+04],
       [1.03140351e+03, 5.54873810e+04, 1.16260270e+09]])

In [334]:
ret = np.cov(X.T)

In [335]:
corr = pd.DataFrame(X).corr(method='kendall')


In [319]:
ret=corr

In [336]:
eigenValues, eigenVectors = np.linalg.eig(ret)


In [337]:
idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]


In [338]:

eigenVectors

array([[ 7.31261319e-06,  5.90392266e-02, -9.99126638e-01],
       [ 5.39914607e-04,  9.98255518e-01,  4.17846927e-02],
       [ 9.99999854e-01, -5.39404546e-04, -1.52539416e-05]])

In [339]:
P = eigenVectors.T.dot(X.T)


In [340]:
print(P.T[:,:2])
dataset1 = P.T[:,:2]

[[1.90086007e+04 1.90922515e-12]
 [2.00240452e+04 2.01182184e-12]
 [4.30034736e+04 4.31916324e-12]
 [5.69968181e+04 5.72439018e-12]
 [7.59774342e+04 7.64238232e-12]
 [5.79952719e+04 5.82867591e-12]
 [8.39820550e+04 8.44599942e-12]
 [1.49950965e+05 1.50580081e-11]
 [3.30069425e+04 3.31563812e-12]
 [6.50004395e+04 6.53053785e-12]
 [7.99832427e+04 8.03477591e-12]
 [5.19985526e+04 5.22636632e-12]
 [8.59729658e+04 8.64843801e-12]
 [1.80221404e+04 1.81113213e-12]
 [8.19731540e+04 8.24011704e-12]
 [7.99852416e+04 8.04392563e-12]
 [2.50333047e+04 2.51716459e-12]
 [2.60307591e+04 2.61491312e-12]
 [2.80306649e+04 2.81729724e-12]
 [2.90331165e+04 2.91819414e-12]
 [2.20329462e+04 2.21396551e-12]
 [4.90211814e+04 4.92761107e-12]
 [4.10255557e+04 4.12179117e-12]
 [2.20339456e+04 2.21321130e-12]
 [2.30333989e+04 2.31478047e-12]
 [2.00360387e+04 2.01446183e-12]
 [2.80336633e+04 2.81840133e-12]
 [3.00315703e+04 3.02051752e-12]
 [4.30054725e+04 4.32120753e-12]
 [1.80211410e+04 1.81207233e-12]
 [7.399052

In [275]:
pca = PCA(2)
pca.fit(X)


PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [276]:
print(pca.components_)
print(pca.explained_variance_)

[[ 8.87150463e-07  4.77268683e-05  9.99999999e-01]
 [ 3.15616027e-03  9.99995018e-01 -4.77294306e-05]]
[1.16260270e+09 1.07243529e+02]


In [277]:
B = pca.transform(X)
print(B)

[[-5.07425008e+04 -1.62346061e+01]
 [-4.97425001e+04 -2.82415213e-01]
 [-2.67425005e+04 -1.03769911e+01]
 [-1.27425005e+04 -1.00452081e+01]
 [ 6.25749910e+03 -1.89551836e+01]
 [-1.17425005e+04 -1.00960937e+01]
 [ 1.42574995e+04 -1.13339028e+01]
 [ 8.02574996e+04 -9.48407009e+00]
 [-3.67425006e+04 -1.09028480e+01]
 [-4.74250012e+03 -2.42708343e+00]
 [ 1.02574994e+04 -1.21429801e+01]
 [-1.77425005e+04 -1.08065560e+01]
 [ 1.62574991e+04 -1.84324829e+01]
 [-5.17425002e+04 -3.18694141e+00]
 [ 1.22574990e+04 -2.02415552e+01]
 [ 1.02574996e+04 -9.14615116e+00]
 [-4.47424995e+04  1.14788779e+01]
 [-4.37424996e+04  9.43115839e+00]
 [-4.17424996e+04  1.03356945e+01]
 [-4.07424995e+04  1.22911113e+01]
 [-4.77424996e+04  9.62207611e+00]
 [-2.07424995e+04  1.03365277e+01]
 [-2.87424995e+04  1.17152020e+01]
 [-4.77424996e+04  9.62523227e+00]
 [-4.67424995e+04  1.05743417e+01]
 [-4.97424995e+04  1.17175250e+01]
 [-4.17424994e+04  1.33356796e+01]
 [-3.97424995e+04  1.12433869e+01]
 [-2.67425004e+04 -7

In [260]:
#chi square +cov
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.61
[[39 29]
 [10 22]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [325]:
#chi+kendall square
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.61
[[39 29]
 [10 22]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [347]:
lda=LDA(n_components=2)
L=lda.fit_transform(X,y)
#L = lda.transform(X)

/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(3, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)


In [327]:
#WITH LDA +chi
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(L, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.81
[[66  2]
 [17 15]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [348]:
#WITH LDA 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(L, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.91
[[65  3]
 [ 6 26]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [174]:
#WITH PCA with correlation as pearson 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.82
[[59  9]
 [ 9 23]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [166]:
#WITH PCA with correlation as kendall 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.85
[[59  9]
 [ 6 26]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [141]:
#WITH PCA with correlation as spearman 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.83
[[57 11]
 [ 6 26]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [278]:
#WITH PCA 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(B, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))



Variance score: 0.86
[[58 10]
 [ 4 28]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [349]:
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X = dataset.iloc[:, :3].values #given marks
y = dataset.iloc[:, 3].values  #predicting history
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test))) 
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))


Variance score: 0.68
[[68  0]
 [32  0]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
