In [48]:
import numpy as np
import pandas as pd
import scipy.linalg as la
from sklearn.decomposition import PCA


In [49]:
dataset = pd.DataFrame( pd.read_csv("diabetes.csv"))

In [50]:

dataset.shape

(768, 9)

In [51]:
X = dataset.iloc[:, :8].values 
y = dataset.iloc[:, 8].values  

In [52]:
mean = X.mean(axis=0)

In [53]:
X= X -mean

In [8]:
def cov1(a, b): 
#     print("hello")
    if len(a) != len(b): 
#         print("here")
        return 
    a_mean = np.mean(a) 
    b_mean = np.mean(b) 
    sum = 0 
    for i in range(0, len(a)): 
        sum += ((a[i] - a_mean) * (b[i] - b_mean)) 
    return sum/(len(a)-1)

def calc_cov(A):
#     print(A[0])
    N,M = A.shape
    n=0;
    ret = np.reshape(np.zeros(M*M),(M,M))
#     print(ret)
    for m in range(0,M):
        for j in range(0,M):
#             print(m,j)
#             print(A.iloc[:,j].values)
            ret[m][j] = (cov1(A[:,m],A[:,j]))/((statistics.stdev(A[:,m]))*statistics.stdev(A[:,j]))
#             print(ret[n][m])
    return ret;

In [54]:
import statistics
ret= calc_cov(X)

NameError: name 'calc_cov' is not defined

In [ ]:
import statistics
ret = np.cov(X.T)
ret

In [55]:
corr = pd.DataFrame(X).corr(method='spearman')


In [56]:
ret=corr

In [57]:
eigenValues, eigenVectors = np.linalg.eig(ret)


In [58]:
idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]


In [59]:

eigenVectors

array([[-0.21333359, -0.51274778, -0.23119757,  0.28475776,  0.41702567,
         0.08103317, -0.57006818,  0.22712261],
       [-0.38709474, -0.11160532, -0.13802066, -0.83028717, -0.05750427,
         0.16831837, -0.22004885, -0.22184705],
       [-0.38887817, -0.22654965,  0.41592502,  0.04110919, -0.37598133,
        -0.67445173, -0.13149325,  0.09606176],
       [-0.40371561,  0.40761311,  0.13529881,  0.2994015 ,  0.31542767,
        -0.04134766, -0.15918072, -0.66058723],
       [-0.32968036,  0.42883498, -0.24185636, -0.1612253 ,  0.43830956,
        -0.329469  ,  0.23491497,  0.51679124],
       [-0.46215626,  0.14236547,  0.39848672,  0.15828568, -0.20382616,
         0.6308298 ,  0.05204353,  0.37429637],
       [-0.23257493,  0.18788144, -0.70183293,  0.2687119 , -0.58001819,
        -0.00603257, -0.09523414, -0.01751814],
       [-0.3377355 , -0.51739151, -0.16230517,  0.12227414,  0.10883383,
         0.04444466,  0.71903316, -0.21475104]])

In [60]:
P = eigenVectors.T.dot(X.T)


In [61]:
print(P.T[:,:2])
dataset1 = P.T[:,:2]

[[  1.95233041 -41.52413086]
 [ 41.87778892 -24.2336126 ]
 [ 16.04740137 -51.05473653]
 ...
 [ -9.19888115  14.36267648]
 [ 33.02707634 -47.05127359]
 [ 37.37214995 -20.54407036]]


In [14]:
pca = PCA(2)
pca.fit(X)


PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [15]:
print(pca.components_)
print(pca.explained_variance_)

[[-2.02176587e-03  9.78115765e-02  1.60930503e-02  6.07566861e-02
   9.93110844e-01  1.40108085e-02  5.37167919e-04 -3.56474430e-03]
 [-2.26488861e-02 -9.72210040e-01 -1.41909330e-01  5.78614699e-02
   9.46266913e-02 -4.69729766e-02 -8.16804621e-04 -1.40168181e-01]]
[13456.57298102   932.76013231]


In [16]:
B = pca.transform(X)
print(B)

[[-75.71465491 -35.95078264]
 [-82.3582676   28.90821322]
 [-74.63064344 -67.90649647]
 ...
 [ 32.11319827   3.3766648 ]
 [-80.21449431 -14.18601977]
 [-81.30814972  21.62149606]]


In [33]:
#WITH PCA with correlation as pearson 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.7239583333333334
[[111  19]
 [ 34  28]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [47]:
#WITH PCA with correlation as kendall 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.7447916666666666
[[112  18]
 [ 31  31]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [62]:
#WITH PCA with correlation as spearman 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(dataset1, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.7447916666666666
[[112  18]
 [ 31  31]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [17]:
#WITH PCA 
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(B, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))



Variance score: 0.7552083333333334
[[116  14]
 [ 33  29]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [63]:
#ORIGINAL
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X = dataset.iloc[:, :8].values #given marks
y = dataset.iloc[:, 8].values  #predicting history
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test))) 
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))


Variance score: 0.8072916666666666
[[119  11]
 [ 26  36]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [64]:
#WITH LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=2)
L=lda.fit_transform(X,y)
#L = lda.transform(X)
from sklearn import datasets, linear_model, metrics 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(L, y, test_size = 0.25, random_state = 0) 
reg = linear_model.LogisticRegression()
reg.fit(X_train, y_train) 
# variance score: 1 means perfect prediction 
print('Variance score: {}'.format(reg.score(X_test, y_test)))
y_pred = reg.predict(X_test)

print(metrics.confusion_matrix(y_test, y_pred))

Variance score: 0.8229166666666666
[[120  10]
 [ 24  38]]


/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(8, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
/Users/nishthagoel/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
